# Generated by Django 5.2.6 on 2025-09-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')]),
        ),
    ]
