# Generated by Django 5.2.6 on 2025-09-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0002_alter_reminderlog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminderlog',
            old_name='set_date',
            new_name='sent_date',
        ),
    ]
