# Generated by Django 5.2.6 on 2025-09-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0003_rename_set_date_reminderlog_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='c2c.fosterplacement'),
        ),
    ]
