# Generated by Django 5.2.6 on 2025-09-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0004_alter_case_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterplacement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
