# Generated by Django 5.2.6 on 2025-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0005_alter_fosterplacement_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservice',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
