# Generated by Django 5.2.6 on 2025-09-26 01:21

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0006_alter_healthservice_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'children'},
        ),
        migrations.AlterModelOptions(
            name='fosterfamily',
            options={'verbose_name_plural': 'FosterFamilies'},
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='immunizations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HepB', 'Hepatitis B'), ('RV1', 'Rotavirus (RV1)'), ('RV5', 'Rotavirus (RV5)'), ('DTaP', 'Diphtheria, tetanus, acellular pertussis'), ('Tdap', 'Tetanus, diphtheria, acellular pertussis'), ('Hib', 'Haemophilus influenzae type b'), ('PCV15', 'Pneumococcal polysaccharide vaccine (PCV15)'), ('PCV20', 'Pneumococcal polysaccharide vaccine (PCV20)'), ('IPV', 'Inactivated poliovirus (IPV)'), ('MMR', 'Measles, mumps, rubella (MMR)'), ('VAR', 'Varicella (VAR)'), ('HepA', 'Hepatitis A (HepA)'), ('HPV', 'Human papillomavirus (HPV)'), ('MenACWY-TT', 'Meningococcal (MenACWY-TT)'), ('IIV3', 'Influenza (IIV3)'), ('COVID_mRNA', 'COVID-19 (1vCOV-mRNA)'), ('COVID_aPS', 'COVID-19 (1vCOV-aPS)')], default=None, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='service',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('well_child', 'Well Child Checkup'), ('immunization(s)', 'Immunization(s)'), ('dental', 'Dental Cleaning')], max_length=33),
        ),
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('HepB', 'Hepatitis B'), ('RV1', 'Rotavirus (RV1)'), ('RV5', 'Rotavirus (RV5)'), ('DTaP', 'Diphtheria, tetanus, acellular pertussis'), ('Tdap', 'Tetanus, diphtheria, acellular pertussis'), ('Hib', 'Haemophilus influenzae type b'), ('PCV15', 'Pneumococcal polysaccharide vaccine (PCV15)'), ('PCV20', 'Pneumococcal polysaccharide vaccine (PCV20)'), ('IPV', 'Inactivated poliovirus (IPV)'), ('MMR', 'Measles, mumps, rubella (MMR)'), ('VAR', 'Varicella (VAR)'), ('HepA', 'Hepatitis A (HepA)'), ('HPV', 'Human papillomavirus (HPV)'), ('MenACWY-TT', 'Meningococcal (MenACWY-TT)'), ('IIV3', 'Influenza (IIV3)'), ('COVID_mRNA', 'COVID-19 (1vCOV-mRNA)'), ('COVID_aPS', 'COVID-19 (1vCOV-aPS)')])),
                ('dose_number', models.PositiveSmallIntegerField()),
                ('total_doses', models.PositiveSmallIntegerField(default=0)),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c2c.child')),
            ],
            options={
                'unique_together': {('child', 'vaccine_name', 'dose_number')},
            },
        ),
    ]
