# Generated by Django 5.2.6 on 2025-09-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0007_alter_child_options_alter_fosterfamily_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
