# Generated by Django 5.2.6 on 2025-09-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0008_casemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseManager',
        ),
    ]
