# Generated by Django 5.2.6 on 2025-09-30 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0009_delete_casemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='c2c.child'),
        ),
    ]
