# Generated by Django 5.2.6 on 2026-04-22 17:27

import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0010_alter_case_child'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservice',
            name='immunizations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HepB', 'Hepatitis B'), ('RV1', 'Rotavirus (RV1)'), ('RV5', 'Rotavirus (RV5)'), ('DTaP', 'Diphtheria, tetanus, acellular pertussis'), ('Tdap', 'Tetanus, diphtheria, acellular pertussis'), ('Hib', 'Haemophilus influenzae type b'), ('PCV15', 'Pneumococcal polysaccharide vaccine (PCV15)'), ('PCV20', 'Pneumococcal polysaccharide vaccine (PCV20)'), ('IPV', 'Inactivated poliovirus (IPV)'), ('MMR', 'Measles, mumps, rubella (MMR)'), ('VAR', 'Varicella (VAR)'), ('HepA', 'Hepatitis A (HepA)'), ('HPV', 'Human papillomavirus (HPV)'), ('MenACWY-TT', 'Meningococcal (MenACWY-TT)'), ('IIV3', 'Influenza (IIV3)'), ('COVID_mRNA', 'COVID-19 (1vCOV-mRNA)'), ('COVID_aPS', 'COVID-19 (1vCOV-aPS)'), ('None', 'None')], default=None, max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='vaccine_name',
            field=models.CharField(choices=[('HepB', 'Hepatitis B'), ('RV1', 'Rotavirus (RV1)'), ('RV5', 'Rotavirus (RV5)'), ('DTaP', 'Diphtheria, tetanus, acellular pertussis'), ('Tdap', 'Tetanus, diphtheria, acellular pertussis'), ('Hib', 'Haemophilus influenzae type b'), ('PCV15', 'Pneumococcal polysaccharide vaccine (PCV15)'), ('PCV20', 'Pneumococcal polysaccharide vaccine (PCV20)'), ('IPV', 'Inactivated poliovirus (IPV)'), ('MMR', 'Measles, mumps, rubella (MMR)'), ('VAR', 'Varicella (VAR)'), ('HepA', 'Hepatitis A (HepA)'), ('HPV', 'Human papillomavirus (HPV)'), ('MenACWY-TT', 'Meningococcal (MenACWY-TT)'), ('IIV3', 'Influenza (IIV3)'), ('COVID_mRNA', 'COVID-19 (1vCOV-mRNA)'), ('COVID_aPS', 'COVID-19 (1vCOV-aPS)'), ('None', 'None')]),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('first_name', 'last_name', 'dob')},
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('child',), name='unique_open_case'),
        ),
        migrations.AddConstraint(
            model_name='fosterplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('child',), name='unique_active_placement'),
        ),
    ]
