# Generated by Django 5.2.6 on 2026-04-22 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0011_alter_healthservice_immunizations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseworker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='c2c.child'),
        ),
        migrations.AlterField(
            model_name='case',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='c2c.fosterplacement'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open'),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='parent1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='parent2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fosterplacement',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='c2c.child'),
        ),
        migrations.AlterField(
            model_name='fosterplacement',
            name='foster_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='c2c.fosterfamily'),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending'),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='c2c.healthservice'),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent'),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
