# Generated by Django 5.2.6 on 2026-04-22 21:11

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0012_alter_case_caseworker_alter_case_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservice',
            name='immunizations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HepB', 'Hepatitis B'), ('RV1', 'Rotavirus (RV1)'), ('RV5', 'Rotavirus (RV5)'), ('DTaP', 'Diphtheria, tetanus, acellular pertussis'), ('Tdap', 'Tetanus, diphtheria, acellular pertussis'), ('Hib', 'Haemophilus influenzae type b'), ('PCV15', 'Pneumococcal polysaccharide vaccine (PCV15)'), ('PCV20', 'Pneumococcal polysaccharide vaccine (PCV20)'), ('IPV', 'Inactivated poliovirus (IPV)'), ('MMR', 'Measles, mumps, rubella (MMR)'), ('VAR', 'Varicella (VAR)'), ('HepA', 'Hepatitis A (HepA)'), ('HPV', 'Human papillomavirus (HPV)'), ('MenACWY-TT', 'Meningococcal (MenACWY-TT)'), ('IIV3', 'Influenza (IIV3)'), ('COVID_mRNA', 'COVID-19 (1vCOV-mRNA)'), ('COVID_aPS', 'COVID-19 (1vCOV-aPS)'), ('None', 'None')], default='', max_length=101),
        ),
    ]
