# Generated by Django 5.2.6 on 2026-04-23 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0013_alter_healthservice_immunizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservice',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 4, 23, 23, 35, 54, 354310, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
