# Generated by Django 5.2.6 on 2026-04-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2c', '0014_alter_healthservice_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosterfamily',
            name='current_occupancy',
        ),
    ]
