# Generated by Django 5.2.6 on 2025-09-18 18:41

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('medications', models.TextField()),
                ('allergies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FosterFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=256)),
                ('max_occupancy', models.IntegerField(default=1)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('parent1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent1', to=settings.AUTH_USER_MODEL)),
                ('parent2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FosterPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('end_reason', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='care2connect.child')),
                ('foster_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='care2connect.fosterfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('caseworker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care2connect.child')),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='care2connect.fosterplacement')),
            ],
        ),
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', multiselectfield.db.fields.MultiSelectField(choices=[('well_child', 'Well Child Checkup'), ('immunization(s)', 'Immunization(s)'), ('dental', 'Dental'), ('vision', 'Vision'), ('hearing', 'Hearing')], max_length=48)),
                ('immunizations', multiselectfield.db.fields.MultiSelectField(choices=[('rsv', 'Respiratory Syncytial Virus (RSV)'), ('hepb', 'Hepatitis B'), ('rv', 'Rotavirus (RV)'), ('dtap', 'Diptheria, Tetanus & Acellular Pertussis (DTaP)'), ('tdap', 'Tetanus, Diptheria, & Acellular Pertussis (TDaP)'), ('hib', 'Haemophilus Influenzae type b (Hib)'), ('pcv15', 'Pneumococcal Conjugate (PCV15)'), ('pcv20', 'Pneumococcal Conjugate (PCV20)'), ('ipv', 'Inactivated Poliovirus (IPV)'), ('covid_mrna', 'COVID-19 (1vCOV-mRNA)'), ('covid_aps', 'COVID-19 (1vCOV-aPS)'), ('iiv3', 'Influenza'), ('mmr', 'Measles, Mumps, Rubella'), ('var', 'Varicella (VAR)'), ('hepa', 'Hepatitis A (HepA)'), ('hpv', 'Human Papillomavirus (HPV)'), ('menacwy-crm', 'Meningococcal (MenACWY-CRM)'), ('menacwy-tt', 'Meningococcal (Meningococcal (MenACWY-TT))'), ('dengue', 'Dengue (DEN4CYD)'), ('mpox', 'Mpox'), ('none', None)], default=None, max_length=124, null=True)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=None, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care2connect.child')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_date', models.DateTimeField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='care2connect.healthservice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
